//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakeErieTrafficSiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Horn_Backup_Alarm_Ok { get; set; }
        public string Horn_Backup_Alarm_Defect { get; set; }
        public string Horn_Backup_Alarm_Notes { get; set; }
        public string Seatbelt_Ok { get; set; }
        public string Seatbelt_Defect { get; set; }
        public string Seatbelt_Notes { get; set; }
        public string Lights_Strobe_Beacon_Ok { get; set; }
        public string Lights_Strobe_Beacon_Defect { get; set; }
        public string Lights_Strobe_Beacon_Notes { get; set; }
        public string Brakes_Parking_Brake_Ok { get; set; }
        public string Brakes_Parking_Brake_Defect { get; set; }
        public string Brakes_Parking_Brake_Notes { get; set; }
        public string Steering_Controls_Ok { get; set; }
        public string Steering_Controls_Defect { get; set; }
        public string Steering_Controls_Notes { get; set; }
        public string Mirrors_Ok { get; set; }
        public string Mirrors_Defect { get; set; }
        public string Mirrors_Notes { get; set; }
        public string Fire_Extinguisher_Ok { get; set; }
        public string Fire_Extinguisher_Defect { get; set; }
        public string Fire_Extinguisher_Notes { get; set; }
        public string Roll_Over_Protection_Ok { get; set; }
        public string Roll_Over_Protection_Defect { get; set; }
        public string Roll_Over_Protection_Notes { get; set; }
    }
}
